---
title: "Snow crab population dynamics model"
author: "Daniel Duplisea, Hilaire Drouineau, Bernard Sainte-Marie"
date: "2024-08-26"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## background

This model was started as matrix population (e.g. Caswell) in 2002. A relatively simple working version was available in 2003. Red Methot and a Co-op student from L'Université de Sherbrooke (Jean-François ??) assisted in this. The project was put on hold until 2007 when a post-doc from France, Hilaire Drouineau, took over model development. Hilaire hugely improved the model and processes. Hilaire also produced a version where some of the time consuming loops were done in C++.

The model was never a completely fitted model, although some sub-processes were fitted to data. The model was intended to be used in an MSE context where it would be the operating model. Therefore, several of the processes could be turned on and off to create alternative operating models.

We never got to the point on taking the work fully through to an MSE.